// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI80XdeiIvhlqZ2AiVC6K9kgRScqYBMlU',
    appId: '1:147747591133:web:92f5b30593204ccbb85c34',
    messagingSenderId: '147747591133',
    projectId: 'fcm-test-caefc',
    authDomain: 'fcm-test-caefc.firebaseapp.com',
    storageBucket: 'fcm-test-caefc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMwiIhS1o-I7HdfPIVsqBvwrOOHgqe-qQ',
    appId: '1:147747591133:android:573a64556418cf39b85c34',
    messagingSenderId: '147747591133',
    projectId: 'fcm-test-caefc',
    storageBucket: 'fcm-test-caefc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLMwZVp-Snyv0PEuwfztlcgbv0pRy1ewA',
    appId: '1:147747591133:ios:3a53c4976d9a928db85c34',
    messagingSenderId: '147747591133',
    projectId: 'fcm-test-caefc',
    storageBucket: 'fcm-test-caefc.appspot.com',
    iosClientId: '147747591133-ohlt2u7mfjb1rs6jglr9ej97no2jv6ic.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmApp',
  );
}
